### ISSUE TITLE
Xcode 9.4.1

### ISSUE THREAD

**Issue by phiren** [marcoconti83/EasyTables#1]
It gives compiler warning:

Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/hiren/Downloads/EasyTables-master-2/Carthage/Build/Mac/ClosureControls.framework

**Comment by marcoconti83** [comment]
Hi @phiren ,

Sorry for getting back to you so late! This is due to a mismatch in Swift versions.

It's possible that you ran Carthage once, then updated Xcode, then you haven't re-run Carthage again with the new version. This would result in the new Xcode trying to use the framework compiled with the old Swift version. To solve, just re-run Carthage.
